# Generated by Django 5.2.1 on 2025-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ship_type', models.CharField(max_length=255)),
                ('gt', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=255)),
                ('emission_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compliance_strategy', models.CharField(max_length=255)),
            ],
        ),
    ]
