# Generated by Django 5.2.1 on 2025-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
