# Generated by Django 5.2.1 on 2026-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='reward_rfnbo_tj',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Reward_RFNBO [TJ]', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='reward_wind',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Reward_wind multiplier [-]', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='total_energy_from_fuels_tj',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total energy from fuels [TJ]', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='total_ghg_emissions_tco2eq',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total GHG emissions [tCO2eq]', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='total_shore_power_tj',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total shore power [TJ]', max_digits=18, null=True),
        ),
    ]
