# Generated by Django 5.2.1 on 2026-02-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ship_reward_rfnbo_tj_ship_reward_wind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_eu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoyageLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(blank=True, max_length=20, unique=True)),
                ('departure_dt', models.DateTimeField()),
                ('arrival_dt', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='core.port')),
                ('departure_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='core.port')),
            ],
        ),
    ]
