# Generated by Django 5.2.1 on 2026-02-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_port_voyageleg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_class', models.CharField(blank=True, default='', max_length=100)),
                ('fuel_type', models.CharField(max_length=255, unique=True)),
                ('lhv_mj_per_kg', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cf_gco2_per_gfuel', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('wtw_total_gco2e_per_mj', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ttw_co2_gco2_per_mj', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('wtt_plus_nonco2_gco2e_per_mj', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_liquid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ship',
            name='reward_rfnbo_tj',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='reward_wind',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='total_energy_from_fuels_tj',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='total_ghg_emissions_tco2eq',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='total_shore_power_tj',
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='fuel_amount_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='core.fuel'),
        ),
    ]
