# Generated by Django 5.2.1 on 2026-02-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fuel_remove_ship_reward_rfnbo_tj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='is_liquid',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='fuel_amount_kg',
        ),
        migrations.CreateModel(
            name='VoyageLegFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fuel')),
                ('voyage_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_items', to='core.voyageleg')),
            ],
            options={
                'unique_together': {('voyage_leg', 'fuel')},
            },
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='fuels',
            field=models.ManyToManyField(related_name='voyage_legs', through='core.VoyageLegFuel', to='core.fuel'),
        ),
    ]
