# Generated by Django 5.2.1 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_fuel_is_liquid_remove_voyageleg_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='voyage_report_type_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
