# Generated by Django 5.2.1 on 2026-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voyageleg_distance_voyageleg_voyage_report_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='shore_power_energy_mj',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='voyagelegfuel',
            name='ch4_slip_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='voyagelegfuel',
            name='lng_engine_mode',
            field=models.CharField(blank=True, choices=[('OTTO', 'Otto'), ('DIESEL', 'Diesel'), ('CERT', 'Certified actual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voyagelegfuel',
            name='n2o_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
