# Generated by Django 5.2.1 on 2026-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voyageleg_shore_power_energy_mj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='cf_ch4_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='cf_n2o_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_group',
            field=models.CharField(blank=True, choices=[('FOSSIL', 'Fossil'), ('BIOFUEL', 'Biofuel'), ('RFNBO', 'RFNBO'), ('SHORE_POWER', 'Shore power')], default='', max_length=20),
        ),
    ]
