# Generated by Django 5.2.1 on 2026-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fuel_cf_ch4_ratio_fuel_cf_n2o_ratio_fuel_fuel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='required_intensity_snapshot_g_per_mj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
