# Generated by Django 5.2.1 on 2026-03-23 14:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_voyageleg_required_intensity_snapshot_g_per_mj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('final_balance_tco2e', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('action_taken', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('BANK', 'Banking'), ('BORROW', 'Borrowing'), ('POOL', 'Pooling'), ('PENALTY', 'Penalty Paid')], default='COMPLIANT', max_length=20)),
                ('penalty_multiplier_level', models.IntegerField(default=0)),
                ('penalty_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('penalty_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_history', to='core.ship')),
            ],
            options={
                'ordering': ['-year', 'ship_id'],
                'unique_together': {('ship', 'year')},
            },
        ),
    ]
