# Generated by Django 5.2.1 on 2026-03-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_compliancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyage_legs', to='core.ship'),
        ),
    ]
