# Generated by Django 5.2.1 on 2026-04-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_voyageleg_ship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='fuel_type',
        ),
    ]
